package com.raulshma.jellyplay.feature.settings

import com.raulshma.jellyplay.core.model.PlatformKind
import com.raulshma.jellyplay.core.model.PlayerType
import com.raulshma.jellyplay.core.model.currentPlatform
import com.raulshma.jellyplay.core.model.platformEngineSupport
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Pins the desktop actuals of the settings platform seams — the JVM half of
 * the platform contracts the screens gate on (each KDoc promises specific
 * degradation behavior that until now had no unit coverage):
 *
 *  - [DesktopLogCollector]: log collection is ALWAYS unavailable (null) so the
 *    send-logs share row never reaches the share sheet.
 *  - [DesktopAppMetaProvider]: when the shell-generated
 *    `desktop-build.properties` is absent (settings-module unit tests, IDE
 *    runs) version falls back to "dev", and the build is always release-style
 *    with API-0 SDK placeholders (no Android rows on desktop).
 *  - [DesktopAboutLibrariesJsonSource]: a missing `aboutlibraries.json`
 *    classpath resource degrades to null (the ViewModel's load-error state),
 *    never a throw.
 *  - [supportsDynamicColor]: desktop has no Material You — the dynamic-theming
 *    row stays hidden.
 *  - [DesktopAppLocaleSetter]: applying a locale is a no-op (OS-level on
 *    desktop).
 *  - [DesktopPlatformIntents]: no per-app notification-settings surface, the
 *    share methods are safe no-ops, and a browse through AWT Desktop swallows
 *    any failure (headless CI, malformed URI) instead of crashing the caller.
 */
class DesktopPlatformActualsTest {

    // -------------------------------------------------------- log collector

    @Test
    fun `desktop log collection always reports unavailable`() {
        val collector = DesktopLogCollector()

        assertNull(collector.collectLogs("1.2.3", "Release", "https://jelly.example"))
        assertNull(collector.collectLogs("1.2.3", "Release", serverAddress = null))
    }

    // ------------------------------------------------------- app meta (jvm)

    @Test
    fun `desktop app meta falls back to dev with release-style placeholders`() {
        val meta = DesktopAppMetaProvider()

        // desktop-build.properties is generated by :apps:desktop's
        // processResources — absent from this module's test classpath, so the
        // documented "dev" fallback applies.
        assertEquals("dev", meta.versionName)
        assertFalse(meta.isDebugBuild, "desktop builds are release-style")
        assertEquals(0, meta.minSdk, "Android SDK rows have no desktop equivalent")
        assertEquals(0, meta.targetSdk)
    }

    // ----------------------------------------------- aboutlibraries source

    @Test
    fun `a missing aboutlibraries classpath resource degrades to null`() {
        val source = DesktopAboutLibrariesJsonSource()

        // The settings module never bundles aboutlibraries.json on the test
        // classpath — the read must return null (→ load-error state), not throw.
        assertNull(source.read())
    }

    // ---------------------------------------------------- dynamic color gate

    @Test
    fun `desktop has no wallpaper-derived dynamic color`() {
        assertFalse(
            settingsCapabilities.supportsDynamicColor,
            "the dynamic-theming row stays hidden on desktop",
        )
    }

    // ------------------------------------------------------ locale setter

    @Test
    fun `desktop locale application is a no-op`() {
        val setter = DesktopAppLocaleSetter()

        setter.setAppLocale("de-DE")
        setter.setAppLocale(null)
    }

    // ------------------------------------------------------ platform intents

    @Test
    fun `desktop has no per-app system notification settings surface`() {
        val intents = DesktopPlatformIntents()

        assertFalse(intents.canOpenSystemNotificationSettings())
        intents.openSystemNotificationSettings() // must be a safe no-op
    }

    @Test
    fun `desktop shares are safe no-ops`() {
        val intents = DesktopPlatformIntents()

        intents.shareLogFile("Logs", "Share logs", "file:///logs.zip")
        intents.shareJson("Preset", "Share preset", "{}")
    }

    @Test
    fun `openUrl swallows a malformed or unopenable target`() {
        val intents = DesktopPlatformIntents()

        // Not a valid URI: AWT Desktop is unavailable (headless) or rejects it —
        // either way the runCatching guard means the caller never sees a throw.
        intents.openUrl("::::not-a-uri")
        assertTrue(true, "reached without an exception")
    }

    // -------------------------------------------- platform / engine support

    @Test
    fun `desktop is the DESKTOP platform with mpv-only engines`() {
        assertEquals(PlatformKind.DESKTOP, currentPlatform)
        assertEquals(listOf(PlayerType.MPV), platformEngineSupport.engines)
        assertEquals(PlayerType.MPV, platformEngineSupport.default)
    }

    // ------------------------------------------------------ capabilities

    @Test
    fun `desktop capabilities hide every row without a desktop backend`() {
        val caps = settingsCapabilities

        assertFalse(caps.supportsDynamicColor)
        assertFalse(caps.supportsNotifications, "no desktop notification backend (NotificationSync no-ops)")
        assertFalse(caps.supportsAppLocaleOverride, "DesktopAppLocaleSetter is a no-op")
        assertFalse(caps.supportsAudioCache, "no desktop audio cache to clear")
        assertFalse(caps.supportsScreenOrientation)
        assertFalse(caps.supportsTouchGestures)
        assertFalse(caps.supportsBiometric, "rememberBiometricGate returns null (DesktopBiometricGate)")
        assertFalse(caps.supportsSystemNotificationSettings)
        assertFalse(caps.supportsLogSharing)
    }

    @Test
    fun `capability flags stay equal to their behavior seams`() {
        // The visibility flag must never outlive the seam's null-ness / query —
        // the pairs are pinned together here so one platform's truth has one
        // review home.
        val intents = DesktopPlatformIntents()
        assertEquals(
            intents.canOpenSystemNotificationSettings(),
            settingsCapabilities.supportsSystemNotificationSettings,
        )
        val collector = DesktopLogCollector()
        assertEquals(
            collector.collectLogs("1.2.3", "Release", "https://jelly.example") != null,
            settingsCapabilities.supportsLogSharing,
        )
        assertEquals(
            desktopBiometricGate != null,
            settingsCapabilities.supportsBiometric,
        )
    }
}
