package com.raulshma.jellyplay.core.model.subtitle

/**
 * wasmJs actuals for the [SubtitleLanguageCodes] resolvers: the browser has no
 * JDK-equivalent locale enumeration that exposes ISO 639-3, so the tables are
 * a static snapshot generated from the same source the nonWeb actuals read at
 * runtime (`Locale.getAvailableLocales()` on Temurin JDK 21, first-locale-wins,
 * 226 languages). The 639-2B↔639-3 overrides and the 3-letter passthrough live
 * in commonMain, so only these four lookups need platform data; codes outside
 * the snapshot simply fall through to the shared raw-code fallbacks.
 */

/** ISO 639-3 → ISO 639-1 (generated; see file KDoc). */
private val ISO3_TO_ISO1: Map<String, String> = mapOf(
"afr" to "af",
"agq" to "agq",
"aka" to "ak",
"amh" to "am",
"ann" to "ann",
"ara" to "ar",
"asa" to "asa",
"asm" to "as",
"ast" to "ast",
"aze" to "az",
"bam" to "bm",
"bas" to "bas",
"bel" to "be",
"bem" to "bem",
"ben" to "bn",
"bez" to "bez",
"bgc" to "bgc",
"bho" to "bho",
"bod" to "bo",
"bos" to "bs",
"bre" to "br",
"brx" to "brx",
"bul" to "bg",
"cat" to "ca",
"ccp" to "ccp",
"ceb" to "ceb",
"ces" to "cs",
"cgg" to "cgg",
"che" to "ce",
"chr" to "chr",
"chv" to "cv",
"ckb" to "ckb",
"cor" to "kw",
"cym" to "cy",
"dan" to "da",
"dav" to "dav",
"deu" to "de",
"dje" to "dje",
"doi" to "doi",
"dsb" to "dsb",
"dua" to "dua",
"dyo" to "dyo",
"dzo" to "dz",
"ebu" to "ebu",
"ell" to "el",
"eng" to "en",
"epo" to "eo",
"est" to "et",
"eus" to "eu",
"ewe" to "ee",
"ewo" to "ewo",
"fao" to "fo",
"fas" to "fa",
"fil" to "fil",
"fin" to "fi",
"fra" to "fr",
"frr" to "frr",
"fry" to "fy",
"ful" to "ff",
"fur" to "fur",
"gla" to "gd",
"gle" to "ga",
"glg" to "gl",
"glv" to "gv",
"gsw" to "gsw",
"guj" to "gu",
"guz" to "guz",
"hau" to "ha",
"haw" to "haw",
"heb" to "he",
"hin" to "hi",
"hrv" to "hr",
"hsb" to "hsb",
"hun" to "hu",
"hye" to "hy",
"ibo" to "ig",
"iii" to "ii",
"ina" to "ia",
"ind" to "id",
"isl" to "is",
"ita" to "it",
"jav" to "jv",
"jgo" to "jgo",
"jmc" to "jmc",
"jpn" to "ja",
"kab" to "kab",
"kal" to "kl",
"kam" to "kam",
"kan" to "kn",
"kas" to "ks",
"kat" to "ka",
"kaz" to "kk",
"kde" to "kde",
"kea" to "kea",
"kgp" to "kgp",
"khm" to "km",
"khq" to "khq",
"kik" to "ki",
"kin" to "rw",
"kir" to "ky",
"kkj" to "kkj",
"kln" to "kln",
"kok" to "kok",
"kor" to "ko",
"ksb" to "ksb",
"ksf" to "ksf",
"ksh" to "ksh",
"kur" to "ku",
"lag" to "lag",
"lao" to "lo",
"lav" to "lv",
"lin" to "ln",
"lit" to "lt",
"lkt" to "lkt",
"lrc" to "lrc",
"ltz" to "lb",
"lub" to "lu",
"lug" to "lg",
"luo" to "luo",
"luy" to "luy",
"mai" to "mai",
"mal" to "ml",
"mar" to "mr",
"mas" to "mas",
"mdf" to "mdf",
"mer" to "mer",
"mfe" to "mfe",
"mgh" to "mgh",
"mgo" to "mgo",
"mkd" to "mk",
"mlg" to "mg",
"mlt" to "mt",
"mni" to "mni",
"mon" to "mn",
"mri" to "mi",
"msa" to "ms",
"mua" to "mua",
"mya" to "my",
"mzn" to "mzn",
"naq" to "naq",
"nde" to "nd",
"nds" to "nds",
"nep" to "ne",
"nld" to "nl",
"nmg" to "nmg",
"nnh" to "nnh",
"nno" to "nn",
"nob" to "nb",
"nor" to "no",
"nus" to "nus",
"nyn" to "nyn",
"oci" to "oc",
"ori" to "or",
"orm" to "om",
"oss" to "os",
"pan" to "pa",
"pcm" to "pcm",
"pis" to "pis",
"pol" to "pl",
"por" to "pt",
"pus" to "ps",
"que" to "qu",
"raj" to "raj",
"rof" to "rof",
"roh" to "rm",
"ron" to "ro",
"run" to "rn",
"rus" to "ru",
"rwk" to "rwk",
"sag" to "sg",
"sah" to "sah",
"san" to "sa",
"saq" to "saq",
"sat" to "sat",
"sbp" to "sbp",
"seh" to "seh",
"ses" to "ses",
"shi" to "shi",
"sin" to "si",
"slk" to "sk",
"slv" to "sl",
"sme" to "se",
"smn" to "smn",
"sms" to "sms",
"sna" to "sn",
"snd" to "sd",
"som" to "so",
"spa" to "es",
"sqi" to "sq",
"srd" to "sc",
"srp" to "sr",
"sun" to "su",
"swa" to "sw",
"swe" to "sv",
"tam" to "ta",
"tat" to "tt",
"tel" to "te",
"teo" to "teo",
"tgk" to "tg",
"tha" to "th",
"tir" to "ti",
"tok" to "tok",
"ton" to "to",
"tuk" to "tk",
"tur" to "tr",
"twq" to "twq",
"tzm" to "tzm",
"uig" to "ug",
"ukr" to "uk",
"urd" to "ur",
"uzb" to "uz",
"vai" to "vai",
"vie" to "vi",
"vun" to "vun",
"wae" to "wae",
"wol" to "wo",
"xho" to "xh",
"xog" to "xog",
"yav" to "yav",
"yid" to "yi",
"yor" to "yo",
"yrl" to "yrl",
"yue" to "yue",
"zgh" to "zgh",
"zho" to "zh",
"zul" to "zu"
)

/** ISO 639-3 → English display name (generated; see file KDoc). */
private val ISO3_TO_DISPLAY: Map<String, String> = mapOf(
"afr" to "Afrikaans",
"agq" to "Aghem",
"aka" to "Akan",
"amh" to "Amharic",
"ann" to "Obolo",
"ara" to "Arabic",
"asa" to "Asu",
"asm" to "Assamese",
"ast" to "Asturian",
"aze" to "Azerbaijani",
"bam" to "Bambara",
"bas" to "Basaa",
"bel" to "Belarusian",
"bem" to "Bemba",
"ben" to "Bangla",
"bez" to "Bena",
"bgc" to "Haryanvi",
"bho" to "Bhojpuri",
"bod" to "Tibetan",
"bos" to "Bosnian",
"bre" to "Breton",
"brx" to "Bodo",
"bul" to "Bulgarian",
"cat" to "Catalan",
"ccp" to "Chakma",
"ceb" to "Cebuano",
"ces" to "Czech",
"cgg" to "Chiga",
"che" to "Chechen",
"chr" to "Cherokee",
"chv" to "Chuvash",
"ckb" to "Central Kurdish",
"cor" to "Cornish",
"cym" to "Welsh",
"dan" to "Danish",
"dav" to "Taita",
"deu" to "German",
"dje" to "Zarma",
"doi" to "Dogri",
"dsb" to "Lower Sorbian",
"dua" to "Duala",
"dyo" to "Jola-Fonyi",
"dzo" to "Dzongkha",
"ebu" to "Embu",
"ell" to "Greek",
"eng" to "English",
"epo" to "Esperanto",
"est" to "Estonian",
"eus" to "Basque",
"ewe" to "Ewe",
"ewo" to "Ewondo",
"fao" to "Faroese",
"fas" to "Persian",
"fil" to "Filipino",
"fin" to "Finnish",
"fra" to "French",
"frr" to "Northern Frisian",
"fry" to "Western Frisian",
"ful" to "Fula",
"fur" to "Friulian",
"gla" to "Scottish Gaelic",
"gle" to "Irish",
"glg" to "Galician",
"glv" to "Manx",
"gsw" to "Swiss German",
"guj" to "Gujarati",
"guz" to "Gusii",
"hau" to "Hausa",
"haw" to "Hawaiian",
"heb" to "Hebrew",
"hin" to "Hindi",
"hrv" to "Croatian",
"hsb" to "Upper Sorbian",
"hun" to "Hungarian",
"hye" to "Armenian",
"ibo" to "Igbo",
"iii" to "Sichuan Yi",
"ina" to "Interlingua",
"ind" to "Indonesian",
"isl" to "Icelandic",
"ita" to "Italian",
"jav" to "Javanese",
"jgo" to "Ngomba",
"jmc" to "Machame",
"jpn" to "Japanese",
"kab" to "Kabyle",
"kal" to "Kalaallisut",
"kam" to "Kamba",
"kan" to "Kannada",
"kas" to "Kashmiri",
"kat" to "Georgian",
"kaz" to "Kazakh",
"kde" to "Makonde",
"kea" to "Kabuverdianu",
"kgp" to "Kaingang",
"khm" to "Khmer",
"khq" to "Koyra Chiini",
"kik" to "Kikuyu",
"kin" to "Kinyarwanda",
"kir" to "Kyrgyz",
"kkj" to "Kako",
"kln" to "Kalenjin",
"kok" to "Konkani",
"kor" to "Korean",
"ksb" to "Shambala",
"ksf" to "Bafia",
"ksh" to "Colognian",
"kur" to "Kurdish",
"lag" to "Langi",
"lao" to "Lao",
"lav" to "Latvian",
"lin" to "Lingala",
"lit" to "Lithuanian",
"lkt" to "Lakota",
"lrc" to "Northern Luri",
"ltz" to "Luxembourgish",
"lub" to "Luba-Katanga",
"lug" to "Ganda",
"luo" to "Luo",
"luy" to "Luyia",
"mai" to "Maithili",
"mal" to "Malayalam",
"mar" to "Marathi",
"mas" to "Masai",
"mdf" to "Moksha",
"mer" to "Meru",
"mfe" to "Morisyen",
"mgh" to "Makhuwa-Meetto",
"mgo" to "Metaʼ",
"mkd" to "Macedonian",
"mlg" to "Malagasy",
"mlt" to "Maltese",
"mni" to "Manipuri",
"mon" to "Mongolian",
"mri" to "Māori",
"msa" to "Malay",
"mua" to "Mundang",
"mya" to "Burmese",
"mzn" to "Mazanderani",
"naq" to "Nama",
"nde" to "North Ndebele",
"nds" to "Low German",
"nep" to "Nepali",
"nld" to "Dutch",
"nmg" to "Kwasio",
"nnh" to "Ngiemboon",
"nno" to "Norwegian Nynorsk",
"nob" to "Norwegian Bokmål",
"nor" to "Norwegian",
"nus" to "Nuer",
"nyn" to "Nyankole",
"oci" to "Occitan",
"ori" to "Odia",
"orm" to "Oromo",
"oss" to "Ossetic",
"pan" to "Punjabi",
"pcm" to "Nigerian Pidgin",
"pis" to "Pijin",
"pol" to "Polish",
"por" to "Portuguese",
"pus" to "Pashto",
"que" to "Quechua",
"raj" to "Rajasthani",
"rof" to "Rombo",
"roh" to "Romansh",
"ron" to "Romanian",
"run" to "Rundi",
"rus" to "Russian",
"rwk" to "Rwa",
"sag" to "Sango",
"sah" to "Yakut",
"san" to "Sanskrit",
"saq" to "Samburu",
"sat" to "Santali",
"sbp" to "Sangu",
"seh" to "Sena",
"ses" to "Koyraboro Senni",
"shi" to "Tachelhit",
"sin" to "Sinhala",
"slk" to "Slovak",
"slv" to "Slovenian",
"sme" to "Northern Sami",
"smn" to "Inari Sami",
"sms" to "Skolt Sami",
"sna" to "Shona",
"snd" to "Sindhi",
"som" to "Somali",
"spa" to "Spanish",
"sqi" to "Albanian",
"srd" to "Sardinian",
"srp" to "Serbian",
"sun" to "Sundanese",
"swa" to "Swahili",
"swe" to "Swedish",
"tam" to "Tamil",
"tat" to "Tatar",
"tel" to "Telugu",
"teo" to "Teso",
"tgk" to "Tajik",
"tha" to "Thai",
"tir" to "Tigrinya",
"tok" to "Toki Pona",
"ton" to "Tongan",
"tuk" to "Turkmen",
"tur" to "Turkish",
"twq" to "Tasawaq",
"tzm" to "Central Atlas Tamazight",
"uig" to "Uyghur",
"ukr" to "Ukrainian",
"urd" to "Urdu",
"uzb" to "Uzbek",
"vai" to "Vai",
"vie" to "Vietnamese",
"vun" to "Vunjo",
"wae" to "Walser",
"wol" to "Wolof",
"xho" to "Xhosa",
"xog" to "Soga",
"yav" to "Yangben",
"yid" to "Yiddish",
"yor" to "Yoruba",
"yrl" to "Nheengatu",
"yue" to "Cantonese",
"zgh" to "Standard Moroccan Tamazight",
"zho" to "Chinese",
"zul" to "Zulu"
)

internal actual fun platformShortCodeToIso3(cleaned: String): String? =
    ISO3_TO_ISO1.entries.firstOrNull { it.value == cleaned }?.key

internal actual fun platformShortCodeToIso1(code: String): String? =
    ISO3_TO_ISO1.entries.firstOrNull { it.value == code.trim().replace('_', '-').substringBefore('-') }?.value

internal actual fun platformIso3ToIso1(iso3: String): String? = ISO3_TO_ISO1[iso3]

internal actual fun platformIso3DisplayName(iso3: String): String? = ISO3_TO_DISPLAY[iso3]
