package com.raulshma.jellyplay.core.database.crypto

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import dagger.hilt.android.qualifiers.ApplicationContext
import java.security.KeyStore
import java.security.SecureRandom
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Encrypts and decrypts short strings (auth tokens) using an Android-Keystore-backed
 * AES-256-GCM key. Used to keep Jellyfin `accessToken` values opaque at rest in Room
 * (§4.10 of the architecture analysis).
 *
 * - Key material lives inside the Android Keystore (hardware-backed on devices that support
 *   it). The key is generated on first use with alias [KEY_ALIAS] and persists across app
 *   restarts and device reboots until the user uninstalls the app.
 * - The ciphertext is Base64-encoded so it round-trips through SQLite TEXT columns safely.
 * - Format: `v1$<iv-base64>$<ct-base64>` — a version prefix leaves room for future key
 *   rotation without breaking existing rows.
 * - `encrypt` is idempotent: passing an already-encrypted value returns it unchanged.
 * - `decrypt` is forward-compatible: passing plaintext (e.g. a row not yet migrated) returns
 *   it unchanged. This makes the migration path safe — a row written before v25 still reads
 *   correctly.
 *
 * Null and empty inputs are passed through unchanged so callers don't need to special-case
 * missing tokens.
 */
@Singleton
class TokenCipher private constructor(
    private val secretKeyProvider: () -> SecretKey,
) {
    /** Production constructor: derives the AES key from the Android Keystore on first use. */
    @Inject
    constructor(@ApplicationContext context: Context) : this(
        secretKeyProvider = { loadKeystoreKey(context) }
    )

    private val secretKey: SecretKey by lazy { secretKeyProvider() }

    /**
     * Encrypts [plaintext]. Returns `null` if input is `null`. Returns the empty string
     * unchanged. Otherwise returns `v1$<iv-base64>$<ct-base64>`. Idempotent.
     */
    fun encrypt(plaintext: String?): String? {
        if (plaintext == null) return null
        if (plaintext.isEmpty()) return plaintext
        if (isEncrypted(plaintext)) return plaintext
        val cipher = Cipher.getInstance(TRANSFORMATION)
        // NOTE: For Keystore-backed AES-GCM keys, the IV must be generated by the
        // Keystore — we cannot supply our own. Omitting GCMParameterSpec here lets the
        // Keystore pick a random IV, which we read back via cipher.iv below.
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        val iv = cipher.iv
        val ct = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        return VERSION_PREFIX +
            Base64.getEncoder().withoutPadding().encodeToString(iv) +
            SEPARATOR +
            Base64.getEncoder().withoutPadding().encodeToString(ct)
    }

    /**
     * Decrypts [ciphertext] produced by [encrypt]. Returns `null` if input is `null`. Returns
     * the empty string unchanged. Plaintext inputs are returned as-is (forward-compatible with
     * pre-migration rows that haven't been encrypted yet).
     */
    fun decrypt(ciphertext: String?): String? {
        if (ciphertext == null) return null
        if (ciphertext.isEmpty()) return ciphertext
        if (!isEncrypted(ciphertext)) return ciphertext
        val parts = ciphertext.removePrefix(VERSION_PREFIX).split(SEPARATOR)
        require(parts.size == 2) { "Malformed ciphertext" }
        val iv = Base64.getDecoder().decode(parts[0])
        val ct = Base64.getDecoder().decode(parts[1])
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.DECRYPT_MODE, secretKey, GCMParameterSpec(TAG_LENGTH_BITS, iv))
        }
        return String(cipher.doFinal(ct), Charsets.UTF_8)
    }

    /** Returns true if [value] was produced by [encrypt]. */
    fun isEncrypted(value: String?): Boolean {
        if (value == null) return false
        return value.startsWith(VERSION_PREFIX)
    }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "jellyplay_token_cipher_v1"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val TAG_LENGTH_BITS = 128
        private const val VERSION_PREFIX = "v1\$"
        private const val SEPARATOR = "\$"

        /**
         * Loads (or creates on first use) the AES-256-GCM key from the Android Keystore.
         * The key persists across app restarts and is identified by [KEY_ALIAS].
         */
        internal fun loadKeystoreKey(context: Context): SecretKey {
            val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
            keyStore.getKey(KEY_ALIAS, null)?.let { return it as SecretKey }
            val keyGenerator = KeyGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_AES,
                ANDROID_KEYSTORE,
            )
            keyGenerator.init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(256)
                    .build()
            )
            return keyGenerator.generateKey()
        }

        /**
         * Build a [TokenCipher] backed by an explicit [SecretKey] instead of the Android
         * Keystore. Production code should NOT call this — it's intended for unit tests
         * running on the JVM where the Keystore provider isn't registered.
         */
        @JvmStatic
        fun forTesting(secretKey: SecretKey): TokenCipher =
            TokenCipher(secretKeyProvider = { secretKey })

        /**
         * Convenience for tests: build a [TokenCipher] whose key is generated in-memory and
         * shared between the returned instance and any subsequent calls in the same test, so
         * encrypt/decrypt round-trip across instances.
         */
        @JvmStatic
        fun forTestingWithPersistentKey(): TokenCipher = TokenCipher(secretKeyProvider = { persistentTestKey })

        private val persistentTestKey: SecretKey by lazy {
            val bytes = ByteArray(32).also { SecureRandom().nextBytes(it) }
            SecretKeySpec(bytes, "AES")
        }
    }
}
