package com.raulshma.jellyplay.desktop

import java.io.ByteArrayInputStream
import java.io.DataInputStream
import javax.imageio.ImageIO
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Structural validation for the committed packaging icon assets
 * (`apps/desktop/packaging/icons/`, generated by the
 * `:apps:desktop:generatePackagingIcons` Gradle task — wave 10A release
 * engineering).
 *
 * These tests parse the binary containers byte-for-byte so a malformed
 * regeneration (wrong header field, truncated entry, drifting sizes) fails
 * here instead of surfacing as a jpackage error or a broken desktop icon.
 * Honest scope note: this proves CONTAINER VALIDITY only. Rendering of the
 * .icns on macOS is untested (no mac host in this room); the Windows .ico and
 * app-image boot were verified empirically (see the wave-10A report).
 */
class PackagingIconAssetsTest {

    private fun iconsDir(): java.nio.file.Path {
        // Test working directory is normally apps/desktop, but walk up defensively
        // so running from another working directory still resolves the assets.
        var dir = java.nio.file.Paths.get("").toAbsolutePath()
        repeat(6) {
            dir.parent?.let { dir = it }
            val candidate = dir.resolve("apps/desktop/packaging/icons")
            if (java.nio.file.Files.isDirectory(candidate)) return candidate
        }
        error("packaging/icons directory not found walking up from $dir")
    }

    private fun asset(name: String): ByteArray =
        java.nio.file.Files.readAllBytes(iconsDir().resolve(name))

    private fun assertPng(data: ByteArray, offset: Int, minSide: Int) {
        assertEquals(0x89.toByte(), data[offset].toByte(), "PNG magic 0x89")
        assertEquals('P'.code, data[offset + 1].toInt(), "PNG magic 'P'")
        val img = ImageIO.read(ByteArrayInputStream(data, offset, data.size - offset))
        assertNotNull(img, "embedded image must decode")
        assertTrue(img.width >= minSide && img.height >= minSide, "expected >= ${minSide}px, got ${img.width}x${img.height}")
    }

    @Test
    fun `linux png decodes at 512 or larger`() {
        assertPng(asset("JellyPlay-linux.png"), offset = 0, minSide = 512)
    }

    @Test
    fun `ico container has seven png entries covering the windows size ladder`() {
        val data = asset("JellyPlay.ico")
        DataInputStream(ByteArrayInputStream(data)).use { input ->
            fun leShort() = input.readUnsignedByte() or (input.readUnsignedByte() shl 8)
            fun leInt(): Int {
                var v = 0
                repeat(4) { v = v or (input.readUnsignedByte() shl (8 * it)) }
                return v
            }
            assertEquals(0, leShort(), "ICONDIR reserved")
            assertEquals(1, leShort(), "ICONDIR type must be icon")
            val count = leShort()
            assertEquals(7, count, "16/24/32/48/64/128/256 ladder")

            // Spec: 256 encodes as 0 in the 1-byte dimension fields.
            data class Entry(val side: Int, val bytesInRes: Int, val imageOffset: Int)
            val entries = buildList {
                repeat(count) {
                    val widthByte = input.readUnsignedByte()
                    val heightByte = input.readUnsignedByte()
                    input.readUnsignedByte() // palette count
                    input.readUnsignedByte() // reserved
                    assertEquals(1, leShort(), "color planes")
                    assertEquals(32, leShort(), "bit depth")
                    val bytesInRes = leInt()
                    val imageOffset = leInt()
                    add(
                        Entry(
                            side = if (widthByte == 0) 256 else widthByte,
                            bytesInRes = bytesInRes,
                            imageOffset = imageOffset,
                        ),
                    )
                    assertEquals(widthByte, heightByte, "square dimension fields")
                }
            }
            assertEquals(listOf(16, 24, 32, 48, 64, 128, 256), entries.map { it.side })

            entries.forEachIndexed { index, entry ->
                val payload = data.copyOfRange(entry.imageOffset, entry.imageOffset + entry.bytesInRes)
                assertPng(payload, offset = 0, minSide = entry.side)
                // Offsets must be tightly packed: first payload starts after the
                // directory, each next one directly after the previous.
                val expectedStart =
                    6 + 16 * count + entries.take(index).sumOf { it.bytesInRes }
                assertEquals(expectedStart, entry.imageOffset, "packed layout for ${entry.side}px")
            }
        }
    }

    @Test
    fun `icns container wraps ic07-ic10 png sub-images with exact lengths`() {
        val data = asset("JellyPlay.icns")
        assertEquals("icns", String(data, 0, 4, Charsets.US_ASCII), "'icns' magic")
        val totalLength = bigEndianInt(data, 4)
        assertEquals(data.size, totalLength, "'icns' total length must cover the whole file")

        val expectedTypes = mapOf("ic07" to 128, "ic08" to 256, "ic09" to 512, "ic10" to 1024)
        var cursor = 8
        while (cursor < data.size) {
            val type = String(data, cursor, 4, Charsets.US_ASCII)
            val entryLength = bigEndianInt(data, cursor + 4)
            assertTrue(type in expectedTypes, "unexpected icns entry type '$type'")
            assertTrue(entryLength > 8, "icns entry '$type' length covers its own header")
            val png = data.copyOfRange(cursor + 8, cursor + entryLength)
            assertEquals(expectedTypes.getValue(type), pngIhdrWidth(png), "sub-image width for '$type'")
            cursor += entryLength
        }
        assertEquals(data.size, cursor, "entries must tile the file exactly")
    }

    /** Reads the width from the PNG IHDR chunk (big-endian u32 at fixed offset 16). */
    private fun pngIhdrWidth(png: ByteArray): Int {
        assertTrue(png[12] == 'I'.code.toByte() && png[13] == 'H'.code.toByte(), "first chunk is IHDR")
        return bigEndianInt(png, 16)
    }

    private fun bigEndianInt(data: ByteArray, off: Int): Int =
        ((data[off].toInt() and 0xFF) shl 24) or ((data[off + 1].toInt() and 0xFF) shl 16) or
            ((data[off + 2].toInt() and 0xFF) shl 8) or (data[off + 3].toInt() and 0xFF)
}
