name: Deploy Landing Page to GitHub Pages

on:
  push:
    branches: [release-web]
    paths:
      - 'website/**'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Minify HTML, CSS, and JS
        run: |
          npm install -g html-minifier-terser clean-css-cli terser
          find website -name '*.html' -exec html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;
          find website/styles -name '*.css' -exec cleancss -o {} {} \;
          find website/scripts -name '*.js' -exec terser {} -c -m -o {} \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
